name: Selenium Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      juice:
        image: bkimminich/juice-shop:latest
        ports:
          - 3000:3000
      selenium-hub:
        image: selenium/hub:4.25.0
        ports:
          - 4442-4444:4442-4444
      chrome:
        image: selenium/node-chrome:4.25.0
        options: >-
          --shm-size=2gb
        env:
          SE_EVENT_BUS_HOST: selenium-hub
          SE_EVENT_BUS_PUBLISH_PORT: 4442
          SE_EVENT_BUS_SUBSCRIBE_PORT: 4443

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Wait for Juice Shop
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:3000 > /dev/null; then
              echo "Juice Shop is up!"
              exit 0
            fi
            echo "Waiting for Juice Shop..."
            sleep 10
          done
          exit 1

      - name: Run Selenium tests
        run: pytest selenium-tests/ -v